### ISSUE TITLE
Fontconfig warning in terminal - Ubuntu 13.04

### ISSUE THREAD

**Issue by ediamin** [sarim/pyfontfixer#2]
After installing pyfontfixer, if I open some app like vlc, deluge etc in terminal, this error shows:

```
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
```

I checked the 50.user.conf file and it says support for `~/.fonts.conf` is deprecated and will be removed in future. It suggests to use `fontconfig/fonts.conf`. I googled and found a solution in http://xubuntugeek.blogspot.com/2013/01/solved-fontconfig-warning.html

The file path should be `~/.config/fontconfig/.fonts.conf`

**Comment by sarim** [comment]
Thank you very much for finding the solution. I'll fix this. Are you using pyfontfixer from this repo ?

**Comment by ediamin** [comment]
No, I downloaded from your openSuse repo http://download.opensuse.org/repositories/home:/sarimkhan/xUbuntu_13.04/i386/

**Comment by sarim** [comment]
I just pushed a commit fixing this. Can you try this from this repo ?
These commands should replace the installed pyfontfixer with updated file.

```
wget -O /tmp/pyfontfixer.py https://raw.github.com/sarim/pyfontfixer/master/pyfontfixer.py
sudo mv /tmp/pyfontfixer.py /usr/share/pyfontfixer/pyfontfixer.py
```

Now you can remove `~/.fonts.conf`, then open pyfontfixer and set your fonts. It should save font config to new location now :)

**Comment by ediamin** [comment]
It doesn't create `.fonts.cont` file now. I started pyfontfixer from terminal and when I click save, it throws following error

```
Traceback (most recent call last):
  File "/usr/share/pyfontfixer/pyfontfixer.py", line 55, in on_button1_clicked
    savefonts(self.mathcs,self.alias,self.sans,self.serif,self.monospace)
  File "/usr/share/pyfontfixer/pyfontfixer.py", line 120, in savefonts
    outputfile = open(self.configpath,"w")
NameError: global name 'self' is not defined

```

**Comment by sarim** [comment]
My bad. Can you try now ? Just re-run the commands again.

**Comment by ediamin** [comment]
oops, now it's my bad. The file name should not start with dot. It should be `fonts.conf` not `.fonts.conf`.

I re-read the blog post I've given in my first post. Sorry for this.

**Comment by sarim** [comment]
Okey, try again now :)

**Comment by ediamin** [comment]
It works perfect now :)
